vpw/config/routes.rb
Rails.application.routes.draw do
  resources :hoagies
  get 'welcome/index'
  root 'welcome#index'
  resources :hoafies
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vpw/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vpw/app/models/hoafy.rb
class Hoafy < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

vpw/app/models/hoagy.rb
class Hoagy < ApplicationRecord

    has_many :ingredient_hoagie
    has_many :ingredients, :through => :ingredient_hoagie
end

vpw/app/models/ingredient.rb
class Ingredient < ApplicationRecord


has_many :ingredient_hoagie
has_many :hoagies, :through => :ingredient_hoagie
end

vpw/app/models/ingredient_hoagie.rb
class IngredientHoagie < ApplicationRecord


belongs_to :ingredient
belongs_to :hoagy
end

vpw/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

vpw/app/controllers/hoafies_controller.rb
class HoafiesController < ApplicationController
  before_action :set_hoafy, only: [:show, :edit, :update, :destroy]

  # GET /hoafies
  # GET /hoafies.json
  def index
    @hoafies = Hoafy.all
  end

  # GET /hoafies/1
  # GET /hoafies/1.json
  def show
  end

  # GET /hoafies/new
  def new
    @hoafy = Hoafy.new
  end

  # GET /hoafies/1/edit
  def edit
  end

  # POST /hoafies
  # POST /hoafies.json
  def create
    @hoafy = Hoafy.new(hoafy_params)

    respond_to do |format|
      if @hoafy.save
        format.html { redirect_to @hoafy, notice: 'Hoafy was successfully created.' }
        format.json { render :show, status: :created, location: @hoafy }
      else
        format.html { render :new }
        format.json { render json: @hoafy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoafies/1
  # PATCH/PUT /hoafies/1.json
  def update
    respond_to do |format|
      if @hoafy.update(hoafy_params)
        format.html { redirect_to @hoafy, notice: 'Hoafy was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoafy }
      else
        format.html { render :edit }
        format.json { render json: @hoafy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoafies/1
  # DELETE /hoafies/1.json
  def destroy
    @hoafy.destroy
    respond_to do |format|
      format.html { redirect_to hoafies_url, notice: 'Hoafy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoafy
      @hoafy = Hoafy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoafy_params
      params.require(:hoafy).permit(:picture, :comment, :userName, :verified, :likes, :hoafieOfWeek)
    end
end

vpw/app/controllers/hoagies_controller.rb
class HoagiesController < ApplicationController
  before_action :set_hoagy, only: [:show, :edit, :update, :destroy]

  # GET /hoagies
  # GET /hoagies.json
  def index
    @hoagies = Hoagy.all
  end

  # GET /hoagies/1
  # GET /hoagies/1.json
  def show
  end

  # GET /hoagies/new
  def new
    @hoagy = Hoagy.new
    @all_ingredients = Ingredient.all
    @hoagy_ingredient = @hoagy.ingredient_hoagie.build
  end

  # GET /hoagies/1/edit
  def edit
  end

  # POST /hoagies
  # POST /hoagies.json
  def create
    @hoagy = Hoagy.new(hoagy_params[:hoagy])
    hoagy_params[:ingredients][:id].each do |ingredient|
      if !ingredient.empty?
        @ingredient.ingredient_hoagie.build(:ingredient_id => ingredient)
      end
    end
    
    respond_to do |format|
      if @hoagy.save
        format.html { redirect_to @hoagy, notice: 'Hoagy was successfully created.' }
        format.json { render :show, status: :created, location: @hoagy }
      else
        format.html { render :new }
        format.json { render json: @hoagy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoagies/1
  # PATCH/PUT /hoagies/1.json
  def update
    respond_to do |format|
      if @hoagy.update(hoagy_params)
        format.html { redirect_to @hoagy, notice: 'Hoagy was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoagy }
      else
        format.html { render :edit }
        format.json { render json: @hoagy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoagies/1
  # DELETE /hoagies/1.json
  def destroy
    @hoagy.destroy
    respond_to do |format|
      format.html { redirect_to hoagies_url, notice: 'Hoagy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoagy
      @hoagy = Hoagy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoagy_params
      params.require(:hoagy).permit(:name, :ingredients, :price)
    end
end

vpw/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new

    
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :price, :maxUsage, :available)
    end
end

vpw/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

vpw/app/helpers/application_helper.rb
module ApplicationHelper
end

vpw/app/helpers/hoafies_helper.rb
module HoafiesHelper
end

vpw/app/helpers/hoagies_helper.rb
module HoagiesHelper
end

vpw/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

vpw/app/helpers/welcome_helper.rb
module WelcomeHelper
end

vpw/app/views/hoafies/_form.html.erb
<%= form_with(model: hoafy, local: true) do |form| %>
  <% if hoafy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hoafy.errors.count, "error") %> prohibited this hoafy from being saved:</h2>

      <ul>
      <% hoafy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :hoafy_picture %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :hoafy_comment %>
  </div>

  <div class="field">
    <%= form.label :userName %>
    <%= form.text_field :userName, id: :hoafy_userName %>
  </div>

  <div class="field">
    <%= form.label :verified %>
    <%= form.check_box :verified, id: :hoafy_verified %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes, id: :hoafy_likes %>
  </div>

  <div class="field">
    <%= form.label :hoafieOfWeek %>
    <%= form.check_box :hoafieOfWeek, id: :hoafy_hoafieOfWeek %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vpw/app/views/hoafies/edit.html.erb
<h1>Editing Hoafy</h1>

<%= render 'form', hoafy: @hoafy %>

<%= link_to 'Show', @hoafy %> |
<%= link_to 'Back', hoafies_path %>

vpw/app/views/hoafies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hoafies</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Comment</th>
      <th>Username</th>
      <th>Verified</th>
      <th>Likes</th>
      <th>Hoafie of the week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoafies.each do |hoafy| %>
      <tr>
        <td><%= image_tag hoafy.picture_url, width: '100%' if hoafy.picture.present? %></td>
        <td><%= hoafy.comment %></td>
        <td><%= hoafy.userName %></td>
        <td><%= hoafy.verified %></td>
        <td><%= hoafy.likes %></td>
        <td><%= hoafy.hoafieOfWeek %></td>
        <td><%= link_to 'Show', hoafy %></td>
        <td><%= link_to 'Edit', edit_hoafy_path(hoafy) %></td>
        <td><%= link_to 'Destroy', hoafy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoafy', new_hoafy_path %>

vpw/app/views/hoafies/new.html.erb
<h1>New Hoafy</h1>

<%= render 'form', hoafy: @hoafy %>

<%= link_to 'Back', hoafies_path %>

vpw/app/views/hoafies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@hoafy.picture_url, width: 600) if @hoafy.picture.present? %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @hoafy.comment %>
</p>

<p>
  <strong>Username:</strong>
  <%= @hoafy.userName %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @hoafy.verified %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @hoafy.likes %>
</p>

<p>
  <strong>Hoafieofweek:</strong>
  <%= @hoafy.hoafieOfWeek %>
</p>

<%= link_to 'Edit', edit_hoafy_path(@hoafy) %> |
<%= link_to 'Back', hoafies_path %>

vpw/app/views/hoagies/_form.html.erb
<%= form_with(model: hoagy, local: true) do |form| %>
  <% if hoagy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hoagy.errors.count, "error") %> prohibited this hoagy from being saved:</h2>

      <ul>
      <% hoagy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hoagy_name %>
  </div>

  <%= fields_for(@hoagy_ingredient) do |ih| %>

  <div class="field">
    <%= ih.label "All Ingredients" %>
    <%= collection_select(:ingredients, :id, @all_ingredients,:id, :name, {}, {:multiple =>true})%>
  </div>
  <% end %>
  

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_field :ingredients, id: :hoagy_ingredients %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :hoagy_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vpw/app/views/hoagies/edit.html.erb
<h1>Editing Hoagy</h1>

<%= render 'form', hoagy: @hoagy %>

<%= link_to 'Show', @hoagy %> |
<%= link_to 'Back', hoagies_path %>

vpw/app/views/hoagies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hoagies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoagies.each do |hoagy| %>
      <tr>
        <td><%= hoagy.name %></td>
        <td><%= hoagy.ingredients %></td>
        <td><%= hoagy.price %></td>
        <td><%= link_to 'Show', hoagy %></td>
        <td><%= link_to 'Edit', edit_hoagy_path(hoagy) %></td>
        <td><%= link_to 'Destroy', hoagy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoagy', new_hoagy_path %>

vpw/app/views/hoagies/new.html.erb
<h1>New Hoagy</h1>

<%= render 'form', hoagy: @hoagy %>

<%= link_to 'Back', hoagies_path %>

vpw/app/views/hoagies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hoagy.name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @hoagy.ingredients %>
</p>

<p>
  <strong>Price:</strong>
  <%= @hoagy.price %>
</p>

<%= link_to 'Edit', edit_hoagy_path(@hoagy) %> |
<%= link_to 'Back', hoagies_path %>

vpw/app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :ingredient_price %>
  </div>

  <div class="field">
    <%= form.label :maxUsage %>
    <%= form.number_field :maxUsage, id: :ingredient_maxUsage %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available, id: :ingredient_available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vpw/app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

vpw/app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Maximal usage</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.price %></td>
        <td><%= ingredient.maxUsage %></td>
        <td><%= ingredient.available %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

vpw/app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

vpw/app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ingredient.price %>
</p>

<p>
  <strong>Maxusage:</strong>
  <%= @ingredient.maxUsage %>
</p>

<p>
  <strong>Available:</strong>
  <%= @ingredient.available %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

vpw/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vpw</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

vpw/app/views/welcome/index.html.erb
<h1>Welcome in the Hoagie to go Webshop</>
<p> click <a href="ingredients"> here </a> to order your hoagie! <p>
<img src="hoagie">